### PR TITLE
Update for new nengo-bones release

### PR DESCRIPTION
**Pull request by drasmuss**
Updates `.nengobones.yml` to be compatible with the changes from https://github.com/nengo/nengo-bones/pull/14.

This caused a change in the seeds, which revealed some random instability in `test_neuron_gradients`.  Reworked that test to make it less seed-dependent.

`pip` was also getting confused about which version of `six` needed to be installed (due to it being required by both `tensorflow` and `nbval` and the lack of full dependency resolution in pip, see https://github.com/pypa/pip/issues/988). So this adds an explicit `six` requirement to clear things up.

### CODE REVIEW

**Comment by hunse** [comment]
Not sure why `test_freeze_obj` is failing here. It should be unrelated to these changes, so very likely there's some non-determinism. I ran the test ~10 times on my own machine and could not replicate, though I was using Python 3.5 and this happened in 3.6.

**Comment by hunse** [comment]
Looking more at it, it looks like the nengo-dl simulator is using float32, whereas the numpy simulator is using float64. What controls that @drasmuss? I'll try to see if I can force that on my machine to replicate the failure.

**Comment by drasmuss** [comment]
That should always be the case (the nengo-dl simulator uses float32 by default), so that's not a unique feature/failure for that test. And you shouldn't have to do anything to reproduce that locally on your machine, that should just happen. But if you wanted to change it to float64 to see the difference, this is the config option https://www.nengo.ai/nengo-dl/config.html#dtype

**Comment by drasmuss** [comment]
Might be that just setting the seed on the network would solve it. It doesn't seem like it should matter, but maybe for certain rare parameterizations you end up with some exaggerated effects from the float32 rounding?

**Comment by hunse** [comment]
I checked on my machine, and it actually uses float32 as well, but doesn't fail. So that's not the problem.

I re-ran the test and it passed, so it's definitely something non-deterministic. I've made issue #89 for it.

Dan, get out of here, you're on vacation!

**Pull request merged**
