### PR TITLE
Update CUDA versions for TF2.4

### PR DESCRIPTION
**Pull request by drasmuss**
TF 2.4 uses CUDA 11.0 and CUDNN 8.0, so we need to switch to installing those in the builds using TF 2.4.

### CODE REVIEW

**Review by hunse — APPROVED** [review]

**Comment by hunse** [comment]
I'm just going to wait and make sure Appveyor passes.

**Comment by drasmuss** [comment]
Added a minor fixup updating the nvidia driver version (since CUDA 11 requires >= 450)

**Comment by hunse** [comment]
Added a fix for that test. Let me know if it looks good, @drasmuss.

**Comment by drasmuss** [comment]
Looks good

**Pull request merged**
