### PR TITLE
Add keras-model.ipynb to ./doc/examples

### PR DESCRIPTION
**Pull request by NickleDave**

### CODE REVIEW

**Comment by drasmuss** [comment]
This looks great, thanks very much for putting it together!

If it's alright with you, I'll add some edits to combine this and https://www.nengo.ai/nengo-dl/examples/pretrained-model.html into the same example.  I think it'd be a nice story "here's how you could add a tf-slim model to nengo-dl, and here's how you'd add a keras model to nengo-dl".

**Comment by NickleDave** [comment]
Yes, definitely alright with me. That will probably help with consistency of tone in the docs too.

**Comment by drasmuss** [comment]
Added a commit merging those two examples.  I ended up putting the Keras example first, since I think it's a better introduction (there's more weirdness associated with setting up the tf-slim TensorNode).  Let me know if that looks good to you, or feel free to suggest any changes (or just make the edits directly).

The only other thing to do before merging is that we need you to sign the [contributor agreement](https://www.nengo.ai/caa.html), which is done by opening a PR adding your name to this file https://github.com/nengo/nengo.github.io/blob/src/people.rst.

Thanks again for your work on this, can definitely say after going through the example in detail that this is a nice addition to the documentation.

**Comment by drasmuss** [comment]
Just a gentle ping on the status of this @NickleDave.  No worries at all if you haven't had a chance to look at it yet, I just wanted to make sure you weren't waiting on me.

**Comment by NickleDave** [comment]
Will look at it tonight! Sorry for the hold-up, it's been on my to-do list, promise

**Comment by NickleDave** [comment]
Just read through it. LGTM! I wouldn't change a thing.

I fetched upstream and rebased on master, hope that didn't mess everything up.

Will submit a separate PR for the contributor agreement

**Comment by NickleDave** [comment]
Oh, actually, one thing.
Do you think it would be a good idea to put a link to the license for the Tensorflow docs since I adapted the example from there? Maybe right after mentioning "from the Tensorflow docs"?

I can insert if if you think that's appropriate / neccesary.
https://github.com/tensorflow/docs/blob/master/LICENSE

**Comment by NickleDave** [comment]
Great! Happy to contribute, and thank you for walking me through the process

**Pull request merged**
